# Generated by Django 5.2.9 on 2026-08-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
